# Ruby
# Package your Ruby project.
# Add steps that install rails, analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/ruby

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'
  
variables:
  BUNDLE_PATH: $(Pipeline.Workspace)/cache/bundler

steps:
- task: UseRubyVersion@0
  inputs:
    versionSpec: '>= 2.5'

- task: CacheBeta@0
  inputs:
    key: |
      bundler
      $(Agent.OS)
      $(Build.SourcesDirectory)/squib/Gemfile.lock
    path: $(BUNDLE_CACHE_PATH)
  displayName: 'Cache bundler'

- script: |
    gem install bundler
    bundler install --retry=3 --jobs=4
  workingDirectory: 'squib'
  displayName: 'bundle install'

- script: rake
  workingDirectory: 'squib'
  displayName: 'rake'

# Remove gitkeep from the build artifact
- task: DeleteFiles@1
  inputs:
    contents: 'squib/_output/gitkeep.txt'
  displayName: 'Remove gitKeep from published artifact'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: 'squib/_output'
    artifactName: printsheets
  displayName: 'Publish printsheets'
